assert(connectToGdb(CE_GDB_HOST,CE_GDB_PORT,{byteOrder='big'}))
local originalX0=assert(readGdbRegister('x0'))
local originalVector=assert(readGdbRegister('v0'))
local edited=string.char(1,2,3,4,5,6,7,8)
assert(writeGdbRegister('x0',edited) and readGdbRegister('x0')==edited)
-- The independent peer changes PC after the first G; later edits must preserve it.
local livePC=assert(readGdbRegister('pc'))
assert(livePC==string.char(0xef,0xcd,0xab,0x89,0,0,0,0x40))
local vector=string.char(0x20,0x21,0x22,0x23,0x24,0x25,0x26,0x27,0x28,0x29,0x2a,0x2b,0x2c,0x2d,0x2e,0x2f)
assert(writeGdbRegister('v0',vector) and readGdbRegister('v0')==vector)
assert(readGdbRegister('x0')==edited and readGdbRegister('pc')==livePC)
assert(writeGdbRegister('v0',originalVector) and writeGdbRegister('x0',originalX0))
assert(readGdbRegister('v0')==originalVector and readGdbRegister('x0')==originalX0 and readGdbRegister('pc')==livePC)
assert(disconnectProcess()); print('GDB_LUA_BANK=PASSED sparse scalar/vector edits and fresh unrelated values preserved')
