#!/usr/bin/env python3
"""lfm2qt — transpile Cheat Engine's Lazarus .lfm forms to Qt .ui layouts and a
feature inventory.

Reads CE's .lfm files from an EXTERNAL checkout (never committed here) and emits:
  * one Qt Designer .ui per form (our own reimplemented layout — clean-room),
  * a Markdown feature inventory: every window's controls + event handlers, which
    doubles as the missing-feature checklist against our GUI.

Usage:
  lfm2qt.py --ce-source <dir> --out-ui <dir> --out-report <file.md>
"""

from __future__ import annotations

import argparse
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from lfm_parser import parse_lfm_file, LfmObject          # noqa: E402
from widget_map import qt_class, is_nonvisual, WIDGET_MAP  # noqa: E402
from gen_ui import generate_ui                             # noqa: E402


def find_lfm(ce_source: str) -> list[str]:
    out = []
    for base, _dirs, files in os.walk(ce_source):
        for f in files:
            if f.lower().endswith(".lfm"):
                out.append(os.path.join(base, f))
    return sorted(out)


def form_inventory(root: LfmObject) -> dict:
    controls, handlers, unknown = [], [], set()
    for node in root.walk():
        hs = [k for k in node.props if k.startswith("On")]
        for h in hs:
            handlers.append(f"{node.props[h]}")
        if node is root:
            continue
        if is_nonvisual(node.type):
            continue
        cap = node.props.get("Caption")
        cap = cap if isinstance(cap, str) and cap != "<binary-skipped>" else ""
        controls.append((node.name, node.type, cap))
        if qt_class(node.type) is None and not is_nonvisual(node.type):
            unknown.add(node.type)
    return {
        "form": root.name,
        "type": root.type,
        "title": root.props.get("Caption", "") if isinstance(root.props.get("Caption"), str) else "",
        "controls": controls,
        "handlers": sorted(set(handlers)),
        "unknown_types": sorted(unknown),
    }


def write_report(inventories: list[dict], path: str) -> None:
    total_controls = sum(len(i["controls"]) for i in inventories)
    total_handlers = sum(len(i["handlers"]) for i in inventories)
    all_unknown: dict[str, int] = {}
    for i in inventories:
        for t in i["unknown_types"]:
            all_unknown[t] = all_unknown.get(t, 0) + 1

    with open(path, "w", encoding="utf-8") as f:
        f.write("# Cheat Engine GUI feature inventory (from .lfm)\n\n")
        f.write("Generated by `tools/lfm2qt` from an external CE checkout. Every "
                "control + handler below is a CE feature; use it as the checklist "
                "for what our Qt GUI still needs.\n\n")
        f.write(f"- Forms: **{len(inventories)}**\n")
        f.write(f"- Controls: **{total_controls}**\n")
        f.write(f"- Distinct event handlers: **{total_handlers}**\n\n")
        if all_unknown:
            f.write("## Control types with no Qt mapping yet\n\n")
            f.write("These LCL types are not in `widget_map.py` and render as bare "
                    "QWidget; add mappings to improve fidelity.\n\n")
            for t, n in sorted(all_unknown.items(), key=lambda kv: -kv[1]):
                f.write(f"- `{t}` — {n} form(s)\n")
            f.write("\n")
        f.write("## Forms\n\n")
        for i in sorted(inventories, key=lambda x: -len(x["controls"])):
            title = f" — {i['title']}" if i["title"] else ""
            f.write(f"### {i['form']} (`{i['type']}`){title}\n\n")
            f.write(f"{len(i['controls'])} controls, {len(i['handlers'])} handlers.\n\n")
            for name, typ, cap in i["controls"]:
                c = f' "{cap}"' if cap else ""
                f.write(f"- `{name}` : {typ}{c}\n")
            f.write("\n")


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--ce-source", required=True, help="path to a CE checkout (external)")
    ap.add_argument("--out-ui", help="directory to write generated .ui files")
    ap.add_argument("--out-report", help="path to write the Markdown inventory")
    ap.add_argument("--limit", type=int, default=0, help="only process N forms (debug)")
    args = ap.parse_args()

    lfms = find_lfm(args.ce_source)
    if args.limit:
        lfms = lfms[:args.limit]
    if not lfms:
        print(f"no .lfm files under {args.ce_source}", file=sys.stderr)
        return 1

    if args.out_ui:
        os.makedirs(args.out_ui, exist_ok=True)

    inventories, gen_ok, gen_fail = [], 0, 0
    for path in lfms:
        try:
            root = parse_lfm_file(path)
        except Exception as e:  # noqa: BLE001
            print(f"parse FAIL {os.path.basename(path)}: {e}", file=sys.stderr)
            gen_fail += 1
            continue
        inventories.append(form_inventory(root))
        if args.out_ui:
            try:
                ui = generate_ui(root)
                base = (root.name or os.path.splitext(os.path.basename(path))[0])
                with open(os.path.join(args.out_ui, base + ".ui"), "w", encoding="utf-8") as f:
                    f.write(ui)
                gen_ok += 1
            except Exception as e:  # noqa: BLE001
                print(f"gen FAIL {os.path.basename(path)}: {e}", file=sys.stderr)
                gen_fail += 1

    if args.out_report:
        write_report(inventories, args.out_report)

    print(f"forms parsed: {len(inventories)}  ui generated: {gen_ok}  failures: {gen_fail}")
    if args.out_report:
        print(f"report: {args.out_report}")
    if args.out_ui:
        print(f"ui dir: {args.out_ui}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
