#!/usr/bin/env python3
"""Generate or verify the native pthread entry bytes against their assembly."""
import argparse
import pathlib
import subprocess
import tempfile


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--write", action="store_true", help="update checked-in bytecode; otherwise verify")
    parser.add_argument("--output-dir", type=pathlib.Path, help="write generated files outside a read-only source tree")
    parser.add_argument("--architecture", choices=("x86_64", "x32", "i386", "arm64"), action="append",
                        help="select architectures to generate/verify (default: all)")
    args = parser.parse_args()
    root = pathlib.Path(__file__).resolve().parent.parent / "platform/linux/thread_entry"
    output_root = args.output_dir or root
    if args.write:
        output_root.mkdir(parents=True, exist_ok=True)
    variants = [("x86_64", ["as", "--64"], "objcopy", "nm", 8, 24),
                ("x32", ["as", "--x32"], "objcopy", "nm", 4, 24),
                ("i386", ["as", "--32"], "objcopy", "nm", 4, 12),
                ("arm64", ["aarch64-linux-gnu-as"], "aarch64-linux-gnu-objcopy", "aarch64-linux-gnu-nm", 8, 32)]
    if args.architecture:
        variants = [variant for variant in variants if variant[0] in args.architecture]
    with tempfile.TemporaryDirectory(prefix="ce-thread-entry-") as directory:
        temporary = pathlib.Path(directory)
        for name, assembler, objcopy, nm, width, stack in variants:
            obj = temporary / f"{name}.o"
            binary = temporary / f"{name}.bin"
            subprocess.run([*assembler, str(root / f"{name}.S"), "-o", str(obj)], check=True)
            subprocess.run([objcopy, "-O", "binary", "--only-section=.text", str(obj), str(binary)], check=True)
            symbols = {}
            for line in subprocess.check_output([nm, "-n", str(obj)], text=True).splitlines():
                address, _, symbol = line.split()
                symbols[symbol] = int(address, 16)
            assert symbols["entry"] == 0
            code = binary.read_bytes()
            rows = ["    " + ", ".join(f"0x{byte:02x}" for byte in code[i:i+12]) + "," for i in range(0, len(code), 12)]
            content = "// Generated by tools/generate-thread-entry.py. Edit the .S source.\nNativeThreadEntry{{\n"
            content += "\n".join(rows) + f"\n}}, {width}, {symbols['published']}, {symbols['returning']}, {stack}, 4}}\n"
            output = output_root / f"{name}.inc"
            if args.write:
                output.write_text(content)
            elif output.read_text() != content:
                raise SystemExit(f"stale native thread bytecode: {output}")
            print(f"{name}: {len(code)} bytes, native stack/return offsets verified")


if __name__ == "__main__":
    main()
